### ISSUE TITLE
Suggest a better design

### ISSUE THREAD

**Issue by THammami01** [THammami01/tabs-saver-ce#2]

**Comment by PSGitHubUser1** [comment]
Hmmm..

**Comment by THammami01** [comment]
@PSGitHubUser1 Propositions are welcome! 🥳

**Comment by PSGitHubUser1** [comment]
What? happened

**Comment by THammami01** [comment]
Propositions for a better design are welcome.

**Comment by PSGitHubUser1** [comment]
i am not suggesting, I am requesting to add the template for better design
I am opening a pull request.. [Issue Template]
Read it and believe me, it will be worth it if it had no mistakes in typo...

And I am suggesting to make a new milestone. Umm? I can't suggest name...

**Comment by THammami01** [comment]
OK. I didn't realize there was a pull request until after I sent the message.
PR is merged.

**Comment by PSGitHubUser1** [comment]
#3

**Comment by PSGitHubUser1** [comment]
Can you add me as maintainer or co-author so that I can try my best to resolve the issues..?

**Comment by THammami01** [comment]
I don't think that's necessary for the time being, but I'll contact you if that's the case.

**Comment by PSGitHubUser1** [comment]
Ok thanks.
